version: '3.4'

services:
  lazer:
    container_name: lazer
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    networks:
      - lazer
  mongo:
    image: mongo
    container_name: lazer_db
    networks: 
      - lazer
    
networks:
  lazer:
    external: true